package opencdk8scdk8sargoworkflowresources

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.ArchiveStrategy",
		reflect.TypeOf((*ArchiveStrategy)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.ArchivedWorkflowDeletedResponse",
		reflect.TypeOf((*ArchivedWorkflowDeletedResponse)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@opencdk8s/cdk8s-argoworkflow-resources.ArgoWorkflowClusterWorkflowTemplate",
		reflect.TypeOf((*ArgoWorkflowClusterWorkflowTemplate)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "addDependency", GoMethod: "AddDependency"},
			_jsii_.MemberMethod{JsiiMethod: "addJsonPatch", GoMethod: "AddJsonPatch"},
			_jsii_.MemberProperty{JsiiProperty: "apiGroup", GoGetter: "ApiGroup"},
			_jsii_.MemberProperty{JsiiProperty: "apiVersion", GoGetter: "ApiVersion"},
			_jsii_.MemberProperty{JsiiProperty: "chart", GoGetter: "Chart"},
			_jsii_.MemberProperty{JsiiProperty: "kind", GoGetter: "Kind"},
			_jsii_.MemberProperty{JsiiProperty: "metadata", GoGetter: "Metadata"},
			_jsii_.MemberProperty{JsiiProperty: "name", GoGetter: "Name"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberMethod{JsiiMethod: "toJson", GoMethod: "ToJson"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_ArgoWorkflowClusterWorkflowTemplate{}
			_jsii_.InitJsiiProxy(&j.Type__cdk8sApiObject)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"@opencdk8s/cdk8s-argoworkflow-resources.ArgoWorkflowCronWorkflow",
		reflect.TypeOf((*ArgoWorkflowCronWorkflow)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "addDependency", GoMethod: "AddDependency"},
			_jsii_.MemberMethod{JsiiMethod: "addJsonPatch", GoMethod: "AddJsonPatch"},
			_jsii_.MemberProperty{JsiiProperty: "apiGroup", GoGetter: "ApiGroup"},
			_jsii_.MemberProperty{JsiiProperty: "apiVersion", GoGetter: "ApiVersion"},
			_jsii_.MemberProperty{JsiiProperty: "chart", GoGetter: "Chart"},
			_jsii_.MemberProperty{JsiiProperty: "kind", GoGetter: "Kind"},
			_jsii_.MemberProperty{JsiiProperty: "metadata", GoGetter: "Metadata"},
			_jsii_.MemberProperty{JsiiProperty: "name", GoGetter: "Name"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberMethod{JsiiMethod: "toJson", GoMethod: "ToJson"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_ArgoWorkflowCronWorkflow{}
			_jsii_.InitJsiiProxy(&j.Type__cdk8sApiObject)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"@opencdk8s/cdk8s-argoworkflow-resources.ArgoWorkflowWorkflowTemplate",
		reflect.TypeOf((*ArgoWorkflowWorkflowTemplate)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "addDependency", GoMethod: "AddDependency"},
			_jsii_.MemberMethod{JsiiMethod: "addJsonPatch", GoMethod: "AddJsonPatch"},
			_jsii_.MemberProperty{JsiiProperty: "apiGroup", GoGetter: "ApiGroup"},
			_jsii_.MemberProperty{JsiiProperty: "apiVersion", GoGetter: "ApiVersion"},
			_jsii_.MemberProperty{JsiiProperty: "chart", GoGetter: "Chart"},
			_jsii_.MemberProperty{JsiiProperty: "kind", GoGetter: "Kind"},
			_jsii_.MemberProperty{JsiiProperty: "metadata", GoGetter: "Metadata"},
			_jsii_.MemberProperty{JsiiProperty: "name", GoGetter: "Name"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberMethod{JsiiMethod: "toJson", GoMethod: "ToJson"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_ArgoWorkflowWorkflowTemplate{}
			_jsii_.InitJsiiProxy(&j.Type__cdk8sApiObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.Arguments",
		reflect.TypeOf((*Arguments)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.Artifact",
		reflect.TypeOf((*Artifact)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.ArtifactLocation",
		reflect.TypeOf((*ArtifactLocation)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.ArtifactPaths",
		reflect.TypeOf((*ArtifactPaths)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.ArtifactRepositoryRef",
		reflect.TypeOf((*ArtifactRepositoryRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.ArtifactRepositoryRefStatus",
		reflect.TypeOf((*ArtifactRepositoryRefStatus)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.ArtifactoryArtifact",
		reflect.TypeOf((*ArtifactoryArtifact)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.Backoff",
		reflect.TypeOf((*Backoff)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.Cache",
		reflect.TypeOf((*Cache)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.ClusterWorkflowTemplate",
		reflect.TypeOf((*ClusterWorkflowTemplate)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.ClusterWorkflowTemplateDeleteResponse",
		reflect.TypeOf((*ClusterWorkflowTemplateDeleteResponse)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.ClusterWorkflowTemplateLintRequest",
		reflect.TypeOf((*ClusterWorkflowTemplateLintRequest)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.ClusterWorkflowTemplateList",
		reflect.TypeOf((*ClusterWorkflowTemplateList)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.ClusterWorkflowTemplateUpdateRequest",
		reflect.TypeOf((*ClusterWorkflowTemplateUpdateRequest)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.Condition",
		reflect.TypeOf((*Condition)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.ContainerNode",
		reflect.TypeOf((*ContainerNode)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.ContainerSetTemplate",
		reflect.TypeOf((*ContainerSetTemplate)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.ContinueOn",
		reflect.TypeOf((*ContinueOn)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.Counter",
		reflect.TypeOf((*Counter)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.CreateCronWorkflowRequest",
		reflect.TypeOf((*CreateCronWorkflowRequest)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.CreateS3BucketOptions",
		reflect.TypeOf((*CreateS3BucketOptions)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.CronWorkflow",
		reflect.TypeOf((*CronWorkflow)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.CronWorkflowDeletedResponse",
		reflect.TypeOf((*CronWorkflowDeletedResponse)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.CronWorkflowList",
		reflect.TypeOf((*CronWorkflowList)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.CronWorkflowResumeRequest",
		reflect.TypeOf((*CronWorkflowResumeRequest)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.CronWorkflowSpec",
		reflect.TypeOf((*CronWorkflowSpec)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.CronWorkflowStatus",
		reflect.TypeOf((*CronWorkflowStatus)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.CronWorkflowSuspendRequest",
		reflect.TypeOf((*CronWorkflowSuspendRequest)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.DAGTask",
		reflect.TypeOf((*DAGTask)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.DAGTemplate",
		reflect.TypeOf((*DAGTemplate)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.Data",
		reflect.TypeOf((*Data)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.DataSource",
		reflect.TypeOf((*DataSource)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.Event",
		reflect.TypeOf((*Event)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.EventResponse",
		reflect.TypeOf((*EventResponse)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.ExecutorConfig",
		reflect.TypeOf((*ExecutorConfig)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.GCSArtifact",
		reflect.TypeOf((*GCSArtifact)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.Gauge",
		reflect.TypeOf((*Gauge)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.GetUserInfoResponse",
		reflect.TypeOf((*GetUserInfoResponse)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.GitArtifact",
		reflect.TypeOf((*GitArtifact)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.GoogleProtobufAny",
		reflect.TypeOf((*GoogleProtobufAny)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.GrpcGatewayRuntimeError",
		reflect.TypeOf((*GrpcGatewayRuntimeError)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.GrpcGatewayRuntimeStreamError",
		reflect.TypeOf((*GrpcGatewayRuntimeStreamError)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.HDFSArtifact",
		reflect.TypeOf((*HDFSArtifact)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.HTTPArtifact",
		reflect.TypeOf((*HTTPArtifact)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.Header",
		reflect.TypeOf((*Header)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.Histogram",
		reflect.TypeOf((*Histogram)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.InfoResponse",
		reflect.TypeOf((*InfoResponse)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.Inputs",
		reflect.TypeOf((*Inputs)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.Link",
		reflect.TypeOf((*Link)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.LintCronWorkflowRequest",
		reflect.TypeOf((*LintCronWorkflowRequest)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.LogEntry",
		reflect.TypeOf((*LogEntry)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.MemoizationStatus",
		reflect.TypeOf((*MemoizationStatus)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.Memoize",
		reflect.TypeOf((*Memoize)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.Metadata",
		reflect.TypeOf((*Metadata)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.MetricLabel",
		reflect.TypeOf((*MetricLabel)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.Metrics",
		reflect.TypeOf((*Metrics)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.Mutex",
		reflect.TypeOf((*Mutex)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.MutexHolding",
		reflect.TypeOf((*MutexHolding)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.MutexStatus",
		reflect.TypeOf((*MutexStatus)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.NodeStatus",
		reflect.TypeOf((*NodeStatus)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.NodeSynchronizationStatus",
		reflect.TypeOf((*NodeSynchronizationStatus)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.NoneStrategy",
		reflect.TypeOf((*NoneStrategy)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.OSSArtifact",
		reflect.TypeOf((*OSSArtifact)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.Outputs",
		reflect.TypeOf((*Outputs)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.Parameter",
		reflect.TypeOf((*Parameter)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.PodGC",
		reflect.TypeOf((*PodGC)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.Prometheus",
		reflect.TypeOf((*Prometheus)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.RawArtifact",
		reflect.TypeOf((*RawArtifact)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.ResourceTemplate",
		reflect.TypeOf((*ResourceTemplate)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.RetryAffinity",
		reflect.TypeOf((*RetryAffinity)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.RetryNodeAntiAffinity",
		reflect.TypeOf((*RetryNodeAntiAffinity)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.RetryStrategy",
		reflect.TypeOf((*RetryStrategy)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.S3Artifact",
		reflect.TypeOf((*S3Artifact)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.ScriptTemplate",
		reflect.TypeOf((*ScriptTemplate)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.SemaphoreHolding",
		reflect.TypeOf((*SemaphoreHolding)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.SemaphoreRef",
		reflect.TypeOf((*SemaphoreRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.SemaphoreStatus",
		reflect.TypeOf((*SemaphoreStatus)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.Sequence",
		reflect.TypeOf((*Sequence)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.Submit",
		reflect.TypeOf((*Submit)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.SubmitOpts",
		reflect.TypeOf((*SubmitOpts)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.SuppliedValueFrom",
		reflect.TypeOf((*SuppliedValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.SuspendTemplate",
		reflect.TypeOf((*SuspendTemplate)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.Synchronization",
		reflect.TypeOf((*Synchronization)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.SynchronizationStatus",
		reflect.TypeOf((*SynchronizationStatus)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.TTLStrategy",
		reflect.TypeOf((*TTLStrategy)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.TarStrategy",
		reflect.TypeOf((*TarStrategy)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.Template",
		reflect.TypeOf((*Template)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.TemplateRef",
		reflect.TypeOf((*TemplateRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.TransformationStep",
		reflect.TypeOf((*TransformationStep)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.UpdateCronWorkflowRequest",
		reflect.TypeOf((*UpdateCronWorkflowRequest)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.UserContainer",
		reflect.TypeOf((*UserContainer)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.ValueFrom",
		reflect.TypeOf((*ValueFrom)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.Version",
		reflect.TypeOf((*Version)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.VolumeClaimGC",
		reflect.TypeOf((*VolumeClaimGC)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.Workflow",
		reflect.TypeOf((*Workflow)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.WorkflowCreateRequest",
		reflect.TypeOf((*WorkflowCreateRequest)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.WorkflowDeleteResponse",
		reflect.TypeOf((*WorkflowDeleteResponse)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.WorkflowEventBinding",
		reflect.TypeOf((*WorkflowEventBinding)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.WorkflowEventBindingList",
		reflect.TypeOf((*WorkflowEventBindingList)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.WorkflowEventBindingSpec",
		reflect.TypeOf((*WorkflowEventBindingSpec)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.WorkflowLintRequest",
		reflect.TypeOf((*WorkflowLintRequest)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.WorkflowList",
		reflect.TypeOf((*WorkflowList)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.WorkflowResubmitRequest",
		reflect.TypeOf((*WorkflowResubmitRequest)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.WorkflowResumeRequest",
		reflect.TypeOf((*WorkflowResumeRequest)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.WorkflowRetryRequest",
		reflect.TypeOf((*WorkflowRetryRequest)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.WorkflowSetRequest",
		reflect.TypeOf((*WorkflowSetRequest)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.WorkflowSpec",
		reflect.TypeOf((*WorkflowSpec)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.WorkflowStatus",
		reflect.TypeOf((*WorkflowStatus)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.WorkflowStep",
		reflect.TypeOf((*WorkflowStep)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.WorkflowStopRequest",
		reflect.TypeOf((*WorkflowStopRequest)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.WorkflowSubmitRequest",
		reflect.TypeOf((*WorkflowSubmitRequest)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.WorkflowSuspendRequest",
		reflect.TypeOf((*WorkflowSuspendRequest)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.WorkflowTemplate",
		reflect.TypeOf((*WorkflowTemplate)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.WorkflowTemplateCreateRequest",
		reflect.TypeOf((*WorkflowTemplateCreateRequest)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.WorkflowTemplateDeleteResponse",
		reflect.TypeOf((*WorkflowTemplateDeleteResponse)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.WorkflowTemplateLintRequest",
		reflect.TypeOf((*WorkflowTemplateLintRequest)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.WorkflowTemplateList",
		reflect.TypeOf((*WorkflowTemplateList)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.WorkflowTemplateRef",
		reflect.TypeOf((*WorkflowTemplateRef)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.WorkflowTemplateSpec",
		reflect.TypeOf((*WorkflowTemplateSpec)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.WorkflowTemplateUpdateRequest",
		reflect.TypeOf((*WorkflowTemplateUpdateRequest)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.WorkflowTerminateRequest",
		reflect.TypeOf((*WorkflowTerminateRequest)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.WorkflowWatchEvent",
		reflect.TypeOf((*WorkflowWatchEvent)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@opencdk8s/cdk8s-argoworkflow-resources.ZipStrategy",
		reflect.TypeOf((*ZipStrategy)(nil)).Elem(),
	)
}
